packages:
  - apps/*
  - packages/*
  - examples/*

overrides:
  postcss: 8.5.16

allowBuilds:
  '@swc/core': true
  cbor-extract: false
  esbuild: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - bufferutil
  - esbuild
  - sharp
  - utf-8-validate
