import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { isMainModule } from "./lib/is-main";

const root = process.cwd();
const artifactPath = resolve(
  root,
  "contracts/out/ChainNameService.sol/ChainNameService.json",
);
const publicAbiPath = resolve(root, "apps/web/public/abi/ChainNameService.json");
const generatedAbiPath = resolve(root, "apps/web/lib/contract/abi.generated.ts");

export async function exportAbi(): Promise<string> {
  const artifact = JSON.parse(await readFile(artifactPath, "utf8")) as { abi?: unknown };
  if (!Array.isArray(artifact.abi)) throw new Error("Foundry artifact does not contain an ABI.");

  const compact = JSON.stringify(artifact.abi);
  const digest = createHash("sha256").update(compact, "utf8").digest("hex");
  await mkdir(dirname(publicAbiPath), { recursive: true });
  await mkdir(dirname(generatedAbiPath), { recursive: true });
  await writeFile(publicAbiPath, compact, "utf8");
  await writeFile(
    generatedAbiPath,
    `/* This file is generated by scripts/export-abi.ts. */\nexport const chainNameServiceAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
    "utf8",
  );
  return digest;
}

if (isMainModule(import.meta.url)) {
  const digest = await exportAbi();
  console.log(`Exported ChainNameService ABI (${digest}).`);
}
