import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { isMainModule } from "./lib/is-main";

const modules = [
  { key: "registry", contract: "ChainNameRegistryV3", symbol: "chainNameRegistryV3Abi" },
  { key: "controller", contract: "ChainNameControllerV3", symbol: "chainNameControllerV3Abi" },
  { key: "resolver", contract: "ChainNameResolverV3", symbol: "chainNameResolverV3Abi" },
  { key: "universalResolver", contract: "ChainNameUniversalResolverV3", symbol: "chainNameUniversalResolverV3Abi" },
  { key: "marketplace", contract: "ChainNameMarketplaceV3", symbol: "chainNameMarketplaceV3Abi" },
  { key: "marketLens", contract: "ChainNameMarketLensV3", symbol: "chainNameMarketLensV3Abi" },
  { key: "migration", contract: "ChainNameMigrationV3", symbol: "chainNameMigrationV3Abi" },
] as const;

export type V3AbiDigests = Record<(typeof modules)[number]["key"], string>;

export async function exportV3Abis(): Promise<V3AbiDigests> {
  const root = process.cwd();
  const generatedPaths = [
    resolve(root, "apps/web/lib/contract/v3-abi.generated.ts"),
    resolve(root, "packages/sdk/src/v3-abi.generated.ts"),
  ];
  const generated: string[] = ["/* This file is generated by scripts/export-v3-abis.ts. */"];
  const digests = {} as V3AbiDigests;

  for (const module of modules) {
    const artifactPath = resolve(
      root,
      `contracts/out/${module.contract}.sol/${module.contract}.json`,
    );
    const artifact = JSON.parse(await readFile(artifactPath, "utf8")) as { abi?: unknown };
    if (!Array.isArray(artifact.abi)) {
      throw new Error(`${module.contract} Foundry artifact does not contain an ABI.`);
    }
    const compact = JSON.stringify(artifact.abi);
    const digest = createHash("sha256").update(compact, "utf8").digest("hex");
    digests[module.key] = digest;

    const publicPath = resolve(root, `apps/web/public/abi/v3/${module.contract}.json`);
    await mkdir(dirname(publicPath), { recursive: true });
    await writeFile(publicPath, compact, "utf8");
    generated.push(
      `export const ${module.symbol} = ${JSON.stringify(artifact.abi, null, 2)} as const;`,
    );
  }

  for (const generatedPath of generatedPaths) {
    await mkdir(dirname(generatedPath), { recursive: true });
    await writeFile(generatedPath, `${generated.join("\n\n")}\n`, "utf8");
  }
  return digests;
}

if (isMainModule(import.meta.url)) {
  const digests = await exportV3Abis();
  console.log(`Exported v3 suite ABIs: ${JSON.stringify(digests)}.`);
}
